### ISSUE TITLE
macos候选词无法横排

### ISSUE THREAD

**Issue by thend03** [fkxxyz/rime-cloverpinyin#110]
mac安装的鼠须管，brew安装的，然后解压clover-schema-1.1.4到用户目录

使用的配置文件内容如下，感觉只有候选词个数和schema生效了，style没有生效
```
patch:
  menu/page_size: 5
  style/horizontal: true
  style/color_scheme: google
  style/font_point: 30
  schema_list:
    - schema: clover
```
想切换横排，目前上面的配置无法生效，有谁知道原因或者如何去查吗

![image](https://user-images.githubusercontent.com/41274496/147521333-9ffded8e-5861-473c-a901-1bc6850a80ce.png)

![image](https://user-images.githubusercontent.com/41274496/147521354-9670a7b3-9945-47f6-8503-8f8dd44bc488.png)
