### ISSUE TITLE
请问这个输入法下应该如何设置默认输入的标点符号是英文的呢?

### ISSUE THREAD

**Issue by liuqin19980818** [fkxxyz/rime-cloverpinyin#120]
我在`clover.schema.yaml`中修改了这里，但是好像没有生效 

```yaml


switches:
  - name: zh_simp_s2t
    reset: 0
    states: [ 简, 繁 ]
  - name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  - name: symbol_support
    reset: 1
    states: [ "无符", "符" ]
  - name: ascii_punct
    reset: 1 #修改了
    states: [ 。，, ．， ]
  - name: full_shape
    reset: 0
    states: [ 半, 全 ]
  - name: ascii_mode
    reset: 0
    states: [ 中, 英 ]
```

**Comment by 10ta** [comment]
同样问题.
使用 **Ctrl+`** 切换的中英文标点, 在切换输入法后会失效

**Comment by 10ta** [comment]
``` yaml
patch:
  switches:
    - name: zh_simp_s2t
      reset: 0
      states: [ 简, 繁 ]
    - name: emoji_suggestion
      reset: 1
      states: [ "�️️\uFE0E", "�️️\uFE0F" ]
    - name: symbol_support
      reset: 1
      states: [ "无符", "符" ]
    - name: ascii_punct
      reset: 1
      states: [ 。，, ．， ]
    - name: full_shape
      reset: 0
      states: [ 半, 全 ]
    - name: ascii_mode
      reset: 0
      states: [ 中, 英 ]
```

**Comment by 10ta** [comment]
> 我在`clover.schema.yaml`中修改了这里，但是好像没有生效
> 
> ```yaml
> switches:
>   - name: zh_simp_s2t
>     reset: 0
>     states: [ 简, 繁 ]
>   - name: emoji_suggestion
>     reset: 1
>     states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
>   - name: symbol_support
>     reset: 1
>     states: [ "无符", "符" ]
>   - name: ascii_punct
>     reset: 1 #修改了
>     states: [ 。，, ．， ]
>   - name: full_shape
>     reset: 0
>     states: [ 半, 全 ]
>   - name: ascii_mode
>     reset: 0
>     states: [ 中, 英 ]
> ```

``` yaml
patch: #一定要放在patch下, 检查缩进
  switches:
    - name: zh_simp_s2t
      reset: 0
      states: [ 简, 繁 ]
    - name: emoji_suggestion
      reset: 1
      states: [ "�️️\uFE0E", "�️️\uFE0F" ]
    - name: symbol_support
      reset: 1
      states: [ "无符", "符" ]
    - name: ascii_punct
      reset: 1
      states: [ 。，, ．， ]
    - name: full_shape
      reset: 0
      states: [ 半, 全 ]
    - name: ascii_mode
      reset: 0
      states: [ 中, 英 ]
```
