### ISSUE TITLE
如何改变后选项打样式

### ISSUE THREAD

**Issue by newbe36524** [fkxxyz/rime-cloverpinyin#144]
如何改变后选项打样式呢，

比如变成竖排，
比如改变字体和字号

纯新手，嘤嘤嘤

这样打配置似乎都不生效
```yaml clover.custom.yaml
patch:
  "style/horizontal": true      # 候選橫排
  "style/inline_preedit": true  # 內嵌編碼（僅支持TSF）
  "style/display_tray_icon": true  # 顯示托
  "style/font_point": 26
```
