### ISSUE TITLE
四叶草没有出现在列表中

### ISSUE THREAD

**Issue by SkyHunterC** [fkxxyz/rime-cloverpinyin#29]
![image](https://user-images.githubusercontent.com/41264239/94356119-6ea41c80-00bd-11eb-982d-fae62dc225f2.png)

![image](https://user-images.githubusercontent.com/41264239/94356140-95625300-00bd-11eb-8a12-ec2b1fac06b8.png)

![image](https://user-images.githubusercontent.com/41264239/94356150-a90db980-00bd-11eb-82fb-2aaf91f46057.png)

**Comment by fkxxyz** [comment]
还需要修改 default.custom.yaml 来定制输入方案列表
参考 
- https://github.com/fkxxyz/rime-cloverpinyin/wiki/linux#%E5%88%87%E6%8D%A2%E5%88%B0%E8%AF%A5%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88
- https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

**Comment by SkyHunterC** [comment]
> 还需要修改 default.custom.yaml 来定制输入方案列表
> 参考
> 
> * https://github.com/fkxxyz/rime-cloverpinyin/wiki/linux#%E5%88%87%E6%8D%A2%E5%88%B0%E8%AF%A5%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88
> * https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

这个yaml我创建了

**Comment by Jacobax** [comment]
一样用不了
deepin20 fcitx-rime
解压到配置文件夹、创建修改default.custom.yaml文件，部署通过，F4只有一个 1.clover，右键方案列表只有 英文 和 clover 两项，选了clover也输入不了中文
win10下正常

**Comment by fkxxyz** [comment]
我猜测可能是缺少了 [rime-prelude](https://github.com/rime/rime-prelude) 
用包管理器安装它，或者直接下载到用户资料夹试试。

详细可以看看部署日志
看看 /tmp 里面有没有 /tmp/rime.fcitx-rime.ERROR 打印它的内容方便排查

**Comment by SkyHunterC** [comment]
> 我猜测可能是缺少了 [rime-prelude](https://github.com/rime/rime-prelude)
> 用包管理器安装它，或者直接下载到用户资料夹试试。
> 
> 详细可以看看部署日志
> 看看 /tmp 里面有没有 /tmp/rime.fcitx-rime.ERROR 打印它的内容方便排查

好像是用户文件夹有压缩包的原因，我重新装了一遍，压缩包原文件没放到用户文件夹内，这次就好了

**Comment by liflux** [comment]
我修改了default.custom.yaml，如下：
```
patch:
  "menu/page_size": 8
  schema_list:
  - schema: pinyin_simp
  - schema: clover
#   - schema: luna_pinyin
#   - schema: luna_pinyin_simp
#   - schema: luna_pinyin_fluency
#   - schema: bopomofo
#   - schema: bopomofo_tw
#   - schema: cangjie5
  - schema: stroke
#   - schema: terra_pinyin
```
能切换到四叶草输入法，但是无法输入中文。
~/.config/ibus/rime/目录列表为
```
$ ls
build                           sync
clover.base.dict.yaml           THUOCL_animal.dict.yaml
clover.dict.yaml                THUOCL_caijing.dict.yaml
clover.key_bindings.yaml        THUOCL_car.dict.yaml
clover.phrase.dict.yaml         THUOCL_chengyu.dict.yaml
clover.schema.yaml              THUOCL_diming.dict.yaml
default.custom.yaml             THUOCL_food.dict.yaml
installation.yaml               THUOCL_IT.dict.yaml
luna_pinyin.userdb              THUOCL_law.dict.yaml
opencc                          THUOCL_lishimingren.dict.yaml
pinyin_simp.schema.custom.yaml  THUOCL_medical.dict.yaml
pinyin_simp.userdb              THUOCL_poem.dict.yaml
sogou_new_words.dict.yaml       user.yaml
stroke.userdb
```
环境为gnome，在Ubuntu 20.04下，用ibus框架。
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
袖珍简化字拼音能启动正常输入。
