### ISSUE TITLE
可否加入中英混合输入？

### ISSUE THREAD

**Issue by 1900forever** [fkxxyz/rime-cloverpinyin#4]
偶然发现的，马上star一个。
我是在macos平台上使用的，加上default.custom.yaml和squirrel.custom.yaml后完成皮肤配色和横盘候选词。

中文输入真的是很流畅，比我之前的配置还要准确一些，只不过在一些词的输入上还是差点意思。比如输入“办到的”，出来的是“半岛的”，直到完成第一次输入。

另外，没有中英文混合输入的话，有的时候确实是不够方便，比如有时候需要输入iOS或者macOS，就必须先完成中文输入再按一下shift键来输入英文。在其他人的配置方案中，通常是使用luna_pinyin.cn_en.dict.yaml来完成英文、中英文混合短语和名词的输入的。不知道未来可不可以也加入类似的方案？

**Comment by fkxxyz** [comment]
感谢star和反馈。

我也是想实现这样一个功能，其实我基于的这些词典里原本是带中英文混合的词汇的，而当时发现一个副作用就是，比如加入了 mac 这个词汇，会导致输入 mac 之后，候选列表里只有一个 mac，那么“马车”、“马超”这些词语就得输全拼也就无法方便的输入了。

即便是我们认为都应该加到候选列表里（搜狗输入法也是这样做的），但是很无奈，权衡之下，我就直接过滤掉了所有带英文的词。

当然也有很多混合词汇不会影响正常的输入，比如“java编程”，候选列表里面就只有这一个没关系，但是要挑选出这些不会影响正常输入的词汇，如何挑选呢，我觉得，还是想办法实全部加到候选列表里更靠谱一些。

现在还没能找到完美的办法。如果要彻底解决这个问题，可能是得改进 librime 的源码了吧。

如果谁有更好的办法一定告诉我。

**Comment by fkxxyz** [comment]
如果你想和别人定制的方案一样暂时解决这个问题，操作也很简单，参考 [导入自定义词库](https://github.com/fkxxyz/rime-cloverpinyin#%E5%AF%BC%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%BA%93)，你可以试试，导入一些没有副作用的混合词语。

建立一个 cn_en.dict.yaml 文件，内容为，后面可以自己定义。

```yaml
name: cn_en
version: "1.0"
sort: by_weight
...
iOS	ios
macOS	macos
```

然后将你想添加的混合词汇加到里面，然后修改 clover.dict.yaml ，最后面加一行

```yaml
name: clover
version: "1"
sort: by_weight

import_tables:
  - clover.base
  - clover.phrase
  - THUOCL_animal
  - THUOCL_caijing
  - THUOCL_car
  - THUOCL_chengyu
  - THUOCL_diming
  - THUOCL_food
  - THUOCL_IT
  - THUOCL_law
  - THUOCL_lishimingren
  - THUOCL_medical
  - THUOCL_poem
  - sogou_new_words
  - cn_en
```
